events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:8000/;
        }

        location /users/ {
            proxy_pass http://user-service:8000/;
        }

        location /cameras/ {
            proxy_pass http://camera-service:8000/;
        }

        location /central/ {
            proxy_pass http://central-service:8000/;
        }

        location /alerts/ {
            proxy_pass http://alert-service:8000/;
        }
    }
}